#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

import os
import secrets
import string
import sys
import tempfile
from datetime import datetime
from pathlib import Path

APP_NAME = "compile_to_exe"

log_file: Path | None = None
_LOG_HANDLE = None
_ORIGINAL_STDOUT = sys.stdout
_ORIGINAL_STDERR = sys.stderr


class TeeStream:
    def __init__(self, primary, secondary) -> None:
        self.primary = primary
        self.secondary = secondary

    @property
    def encoding(self):
        return getattr(self.primary, "encoding", "utf-8")

    def write(self, value: str) -> int:
        written = self.primary.write(value)
        self.primary.flush()
        self.secondary.write(value)
        self.secondary.flush()
        return written

    def flush(self) -> None:
        self.primary.flush()
        self.secondary.flush()

    def isatty(self) -> bool:
        return bool(getattr(self.primary, "isatty", lambda: False)())


def tool_file() -> Path:
    raw = os.environ.get("CYXLABS_COMPILE_TO_EXE_TOOL_FILE")
    if raw:
        return Path(raw).expanduser().resolve()
    return Path(sys.argv[0]).expanduser().resolve()


def project_root() -> Path:
    raw = os.environ.get("CYXLABS_COMPILE_TO_EXE_PROJECT_ROOT")
    if raw:
        return Path(raw).expanduser().resolve()
    try:
        return tool_file().parents[4]
    except IndexError:
        return tool_file().parent


def provider_dir() -> Path:
    raw = os.environ.get("CYXLABS_COMPILE_TO_EXE_PROVIDER_DIR")
    if raw:
        return Path(raw).expanduser().resolve()
    return project_root() / "platform" / "tools"


def load_provider_modules() -> None:
    path = str(provider_dir())
    if path not in sys.path:
        sys.path.insert(0, path)


def debug(message: str) -> None:
    print(f"[{APP_NAME}] {message}", flush=True)


def debug_header(title: str) -> None:
    print("", flush=True)
    print("=" * 78, flush=True)
    print(f"[{APP_NAME}] {title}", flush=True)
    print("=" * 78, flush=True)


def fail(message: str, exit_code: int = 1) -> None:
    print(f"[{APP_NAME}] ERROR: {message}", file=sys.stderr, flush=True)
    raise SystemExit(exit_code)


def generate_random_part(quiet: bool = False) -> str:
    load_provider_modules()
    try:
        from random_string_provider import generate_string
        value = generate_string(length=64, variant=1)
        if not quiet:
            debug("Random string requested from platform/tools/random_string_provider.py.")
        return value
    except Exception as exc:
        if not quiet:
            debug(f"random_string_provider.py unavailable or failed: {exc!r}")
        chars = string.digits + string.ascii_lowercase + string.ascii_uppercase
        value = "".join(secrets.choice(chars) for _ in range(64))
        if not quiet:
            debug("Random string generated by internal fallback.")
        return value


def generate_build_timestamp(quiet: bool = False) -> str:
    load_provider_modules()
    try:
        from timestamp_provider import generate_combined_timestamp
        value = generate_combined_timestamp(variants=[4, 14])
        if not quiet:
            debug("Timestamp requested from platform/tools/timestamp_provider.py.")
        return value
    except Exception as exc:
        if not quiet:
            debug(f"timestamp_provider.py unavailable or failed: {exc!r}")
        value = datetime.now().strftime("%Y_%m_%d_%H_%M_%S_%f")[:-4]
        if not quiet:
            debug("Timestamp generated by internal fallback.")
        return value


def setup_logging() -> None:
    global log_file, _LOG_HANDLE
    if _LOG_HANDLE is not None:
        return

    own_stem = tool_file().stem
    timestamp = generate_build_timestamp(quiet=True)
    random_part = generate_random_part(quiet=True)
    candidate = Path(tempfile.gettempdir()) / f"{own_stem}_{timestamp}_{random_part}.log"

    try:
        candidate.parent.mkdir(parents=True, exist_ok=True)
        _LOG_HANDLE = candidate.open("a", encoding="utf-8", buffering=1)
    except Exception as exc:
        print(
            f"[{APP_NAME}] ERROR: Could not create log file: {candidate} ({exc!r})",
            file=sys.stderr,
            flush=True,
        )
        raise SystemExit(1)

    log_file = candidate
    sys.stdout = TeeStream(_ORIGINAL_STDOUT, _LOG_HANDLE)
    sys.stderr = TeeStream(_ORIGINAL_STDERR, _LOG_HANDLE)


def normalize_path(value: str) -> Path:
    return Path(value).expanduser().resolve()


def ensure_directory_writable(directory: Path, label: str) -> None:
    debug(f"Validating writable directory for {label}: {directory}")
    try:
        directory.mkdir(parents=True, exist_ok=True)
    except Exception as exc:
        fail(f"Could not create directory for {label}: {directory} ({exc!r})")

    if not directory.exists():
        fail(f"Directory for {label} does not exist after creation attempt: {directory}")
    if not directory.is_dir():
        fail(f"Path for {label} is not a directory: {directory}")

    test_file = directory / f".compile_to_exe_write_test_{generate_random_part()}.tmp"
    try:
        test_file.write_text("write test", encoding="utf-8")
        test_file.unlink()
    except Exception as exc:
        fail(f"Directory for {label} is not writable: {directory} ({exc!r})")
    debug(f"Writable directory validation successful for {label}: {directory}")
